// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MythRPG.Data;

#nullable disable

namespace MythRPG.Migrations
{
    [DbContext(typeof(MythRPGContext))]
    partial class MythRPGContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BonusTrait", b =>
                {
                    b.Property<int>("BonusesBonusId")
                        .HasColumnType("int");

                    b.Property<int>("TraitId")
                        .HasColumnType("int");

                    b.HasKey("BonusesBonusId", "TraitId");

                    b.HasIndex("TraitId");

                    b.ToTable("BonusTrait");
                });

            modelBuilder.Entity("CharacterSpell", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SpellsSpellId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "SpellsSpellId");

                    b.HasIndex("SpellsSpellId");

                    b.ToTable("CharacterSpell");
                });

            modelBuilder.Entity("CharacterTrait", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("TraitsTraitId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "TraitsTraitId");

                    b.HasIndex("TraitsTraitId");

                    b.ToTable("CharacterTrait");
                });

            modelBuilder.Entity("MythRPG.Core.Bonus", b =>
                {
                    b.Property<int>("BonusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BonusId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Modifies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BonusId");

                    b.ToTable("Bonuses");

                    b.HasData(
                        new
                        {
                            BonusId = 1,
                            Amount = 2,
                            Modifies = "Prowess",
                            Type = "Other"
                        },
                        new
                        {
                            BonusId = 2,
                            Amount = 2,
                            Modifies = "Arcana",
                            Type = "Other"
                        });
                });

            modelBuilder.Entity("MythRPG.Core.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<string>("Armour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CharacterClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CharacterLevel")
                        .HasColumnType("int");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Knowledge")
                        .HasColumnType("int");

                    b.Property<int>("Might")
                        .HasColumnType("int");

                    b.Property<string>("MythicPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryTrait")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryTrait")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Shield")
                        .HasColumnType("bit");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TertiaryTrait")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Agility = 0,
                            CharacterClass = "Witch",
                            CharacterLevel = 4,
                            CharacterName = "Briar Elderose",
                            Charisma = 0,
                            Knowledge = 0,
                            Might = 0,
                            Species = ""
                        });
                });

            modelBuilder.Entity("MythRPG.Core.Spell", b =>
                {
                    b.Property<int>("SpellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpellId"));

                    b.Property<string>("Casting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Concentration")
                        .HasColumnType("bit");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Effect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Range")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpellId");

                    b.ToTable("Spells");

                    b.HasData(
                        new
                        {
                            SpellId = 1,
                            Casting = "Basic Action",
                            Colour = "Black",
                            Concentration = false,
                            Cost = 1,
                            Duration = "Round",
                            Effect = "Choose a target within range and make a spell attack, contested by their Magical Defence. On a success, the target is Restrained until the start of your next turn.",
                            Name = "Entangle",
                            Range = "Short",
                            Type = "Debuff"
                        },
                        new
                        {
                            SpellId = 2,
                            Casting = "Basic Action",
                            Colour = "White",
                            Concentration = false,
                            Cost = 3,
                            Duration = "Instant",
                            Effect = "Make a ranged spell attack against a creature, contested by their Magical Defence. On a hit, deal 3d6+C Radiant damage to the creature. This damage increases by 1d6 if they are a Fiend or Undead.",
                            Name = "Divine Bolt",
                            Range = "Short",
                            Type = "Attack"
                        },
                        new
                        {
                            SpellId = 3,
                            Casting = "Basic Action",
                            Colour = "Red",
                            Concentration = false,
                            Cost = 2,
                            Duration = "Instant",
                            Effect = "Choose a willing creature within range. They regain 1d8+C Health.",
                            Name = "Invigorating Touch",
                            Range = "Melee",
                            Type = "Healing"
                        });
                });

            modelBuilder.Entity("MythRPG.Core.Trait", b =>
                {
                    b.Property<int>("TraitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraitId"));

                    b.Property<string>("ActionCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TraitId");

                    b.ToTable("Traits");

                    b.HasData(
                        new
                        {
                            TraitId = 1,
                            ActionCost = "None",
                            Description = "Add 2 points to your Prowess pool total. You may take this trait multiple times.",
                            Name = "Increased Prowess",
                            ResourceCost = "None",
                            Source = "Class Trait"
                        },
                        new
                        {
                            TraitId = 2,
                            ActionCost = "None",
                            Description = "Add 2 points to your Arcana pool total. You may take this trait multiple times.",
                            Name = "Improved Arcanum",
                            ResourceCost = "None",
                            Source = "Class Trait"
                        });
                });

            modelBuilder.Entity("MythRPG.Core.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "KAajsw11&",
                            Username = "Spleen"
                        },
                        new
                        {
                            UserId = 2,
                            Password = "GQtzkr79$",
                            Username = "Sean"
                        },
                        new
                        {
                            UserId = 3,
                            Password = "DTajej63*",
                            Username = "Chelsea"
                        },
                        new
                        {
                            UserId = 4,
                            Password = "HGuxmk93~",
                            Username = "Amarii"
                        },
                        new
                        {
                            UserId = 5,
                            Password = "MUdydn97%",
                            Username = "Corn"
                        },
                        new
                        {
                            UserId = 6,
                            Password = "OEnxmu56!",
                            Username = "Liz"
                        },
                        new
                        {
                            UserId = 7,
                            Password = "RUlvyl12?",
                            Username = "Daeni"
                        },
                        new
                        {
                            UserId = 8,
                            Password = "PLrwgc94-",
                            Username = "Kyle"
                        },
                        new
                        {
                            UserId = 9,
                            Password = "CXejuc08@",
                            Username = "UGW"
                        },
                        new
                        {
                            UserId = 10,
                            Password = "QIzkwj58^",
                            Username = "Kira"
                        },
                        new
                        {
                            UserId = 11,
                            Password = "VXqmze90+",
                            Username = "Kat"
                        });
                });

            modelBuilder.Entity("BonusTrait", b =>
                {
                    b.HasOne("MythRPG.Core.Bonus", null)
                        .WithMany()
                        .HasForeignKey("BonusesBonusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MythRPG.Core.Trait", null)
                        .WithMany()
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSpell", b =>
                {
                    b.HasOne("MythRPG.Core.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MythRPG.Core.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellsSpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterTrait", b =>
                {
                    b.HasOne("MythRPG.Core.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MythRPG.Core.Trait", null)
                        .WithMany()
                        .HasForeignKey("TraitsTraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MythRPG.Core.Character", b =>
                {
                    b.HasOne("MythRPG.Core.User", null)
                        .WithMany("Characters")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MythRPG.Core.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
